// Code generated by "stringer -type=LogLineType"; DO NOT EDIT

package scanner

import "fmt"

// LogLineTypeName ...
const LogLineTypeName = "BeforeFirstStepStepInfoHeaderStepLogStepInfoFooterBetweenStepsBuildSummaryStepInfoHeaderOrBuildSummarySectionStarterAfterBuildSummary"

// LogLineTypeIndex ...
var LogLineTypeIndex = [...]uint8{0, 15, 29, 36, 50, 62, 74, 116, 133}

func (i LogLineType) String() string {
	if i < 0 || i >= LogLineType(len(LogLineTypeIndex)-1) {
		return fmt.Sprintf("LogLineType(%d)", i)
	}
	return LogLineTypeName[LogLineTypeIndex[i]:LogLineTypeIndex[i+1]]
}
